version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2204:current
    resource_class: large
    steps:
      - checkout
      - run:
          name: Install Node.js
          command: |
            curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
            sudo apt-get install -y nodejs
      - run:
          name: Install dependencies
          command: npm install
      - run:
          name: Run tests
          command: npm run test
      - run:
          name: Build parcel site
          command: npm run build

workflows:
  build_and_test:
    jobs:
      - build
