name: Proof HTML
on:
  push:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: anishathalye/proof-html@v1.1.0
        with:
          directory: ./
      - name: Check changes in stories
        uses: netlify/actions/diff-includes@master
        with:
          args: docs
